In [2]:
import random
import numpy as np
from itertools import accumulate

In [3]:

n0 = 0
n = 0

random_walk = []
for _ in range(1000):
    n = n + (2 * random.randint(0, 1) - 1)
    random_walk.append(n)

## NumPy
It's very fast but takes more memory

In [4]:
a = np.array([0, 1, 3])
a

array([0, 1, 3])

In [5]:
a.dtype

dtype('int32')

In [6]:
a = np.array([[1., 0., 0.],
              [0., 1., 0.],
              [0., 0., 1.]])

a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
x = np.zeros(5)
x

x = np.zeros([5, 5,])
x
    

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

NameError: name 'lalallaal' is not defined